name: Build and deploy to Azure Israel Central

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/israelkariti/meitav-vm-browser-login:latest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3179BC3B125457380EE8F7771FFAF3B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AC9719E52844A7F997C30D3C1BC302E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A5E3FBDC4F134C16918ABB67AABEE5D2 }}

      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'meitav-vm-browser-login-2'
          images: 'ghcr.io/israelkariti/meitav-vm-browser-login:latest'
